version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=mainpingdash.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: "sqlite:3"
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
